services:
  # A Docker web service
  - type: web
    name: surch-backend
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn inference:app --host 0.0.0.0 --port $PORT